name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test with JaCoCo
      run: | 
        cd backend
        mvn clean verify
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: List files for debugging
      run: find . -name jacoco.xml

    - name: Generate Coverage Badge
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: backend/target/site/jacoco/jacoco.xml
        badge: true
        output: both
        
