name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test with JaCoCo
      run: | 
        cd backend
        mvn clean verify
      env:
        JWT_SECRET: dummy-secret-for-tests

    - name: Generate Coverage Badge
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: target/site/jacoco/jacoco.xml
        badge: true
        output: both
        
