name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test Backend
      working-directory: backend
      run: mvn clean verify
      env:
        MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: jacoco-badge-generator
      uses: cicirello/jacoco-badge-generator@v2.12.0
      with:
        jacoco-csv-file: backend/target/site/jacoco/jacoco.csv

    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'j-mikolajczyk'
          git config --global user.email '124541592@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi

